import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Nav } from "@/components/nav";
import { PageTransition } from "@/components/page-transition";
import { RectangleTransition } from "@/components/rectangle-transition";

import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: {
    default: "Субтропіка",
    template: "%s | Субтропіка",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <RectangleTransition />
        <Nav />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
